// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhSLZMe9Rc5FcT-GdFsW8lkY9piJZykqo',
    appId: '1:27854576367:web:16e7a117ceb83fe42d191a',
    messagingSenderId: '27854576367',
    projectId: 't-ecommerceapp',
    authDomain: 't-ecommerceapp.firebaseapp.com',
    storageBucket: 't-ecommerceapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVAq_TxrffOSgHYz65RsEohDr3wW0vCrU',
    appId: '1:27854576367:android:45b27b5c776b1a982d191a',
    messagingSenderId: '27854576367',
    projectId: 't-ecommerceapp',
    storageBucket: 't-ecommerceapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxv2_VR-45Car-FDhoR-35HrYv4nq2_s',
    appId: '1:27854576367:ios:aa372f8cad427ccf2d191a',
    messagingSenderId: '27854576367',
    projectId: 't-ecommerceapp',
    storageBucket: 't-ecommerceapp.appspot.com',
    androidClientId: '27854576367-gfoqlg9ivuctv18a0mgg11utkc1ggve1.apps.googleusercontent.com',
    iosClientId: '27854576367-poentvo7hi7a1htr3adp475sg3v9dfmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingWithTEcommerce2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxv2_VR-45Car-FDhoR-35HrYv4nq2_s',
    appId: '1:27854576367:ios:d9b9e0063dd3032d2d191a',
    messagingSenderId: '27854576367',
    projectId: 't-ecommerceapp',
    storageBucket: 't-ecommerceapp.appspot.com',
    androidClientId: '27854576367-gfoqlg9ivuctv18a0mgg11utkc1ggve1.apps.googleusercontent.com',
    iosClientId: '27854576367-76uskqkv66c6j6doe6heigl24q3dhd2f.apps.googleusercontent.com',
    iosBundleId: 'com.example.codingWithTEcommerce2.RunnerTests',
  );
}
